# Site settings
name: Fastiraz
title: Fastiraz
description: Just a student with dreams to achieve.
url: https://Fastiraz.github.io/
baseurl: ''
email: F@gmail.com
#cover: https://bchiang7.github.io/img/og.png
logo: https://Fastiraz.github.io/img/me.png
#resume: https://bchiang7.github.io/resume.pdf
social:
<<<<<<< HEAD
  - title: email
    url: mailto:F@gmail.com
=======
  - title: discord
    url: https://discord.gg/khaUkXxneH
>>>>>>> 07db6836be9d2bc2f5c9d4dc179c55138212d902
  - title: github
    url: https://github.com/Fastiraz
  - title: docker
    url: https://hub.docker.com/u/fastiraz
  - title: replit
    url: https://replit.com/@Fastiraz
  - title: twitter
    url: https://twitter.com/Fastiraz
  - title: instagram
    url: https://www.instagram.com/fastiraz/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
