# Site settings
name: Fastiraz
title: Fastiraz | Study Cybersecurity/Sysadmin/Dev
description: Just a student with dreams to achieve.
url: https://Fastiraz.github.io/
baseurl: ''
email: Fastiraz@gmail.com
#cover: https://bchiang7.github.io/img/og.png
#logo: https://bchiang7.github.io/img/emojis/technologist.png
#resume: https://bchiang7.github.io/resume.pdf
social:
  - title: email
    url: mailto:Fastiraz@gmail.com
  - title: github
    url: https://github.com/Fastiraz
  - title: replit
    url: https://replit.com/@Fastiraz
  - title: twitter
    url: https://twitter.com/Fastiraz
  - title: instagram
    url: https://www.instagram.com/fastiraz/
  #- title: codepen
  #  url: http://codepen.io/bchiang7
  #- title: linkedin
  #  url: https://www.linkedin.com/in/bchiang7

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
