# Site settings
name: Fastiraz
title: Fastiraz
description: Just a student with dreams to achieve.
url: https://Fastiraz.github.io/
baseurl: ''
email: 
#cover: https://Fastiraz.github.io/img/og.png
logo: https://Fastiraz.github.io/img/me.png
#resume: https://Fastiraz.github.io/resume.pdf
social:
  #- title: email
  #  url: mailto:
  - title: Doc
    url: https://fastiraz.gitbook.io/doc/
  - title: discord
    url: https://discord.gg/khaUkXxneH
  - title: github
    url: https://github.com/Fastiraz
  #- title: docker
  #  url: https://hub.docker.com/u/fastiraz
  - title: twitter
    url: https://twitter.com/Fastiraz
  #- title: instagram
  #  url: https://www.instagram.com/fastiraz/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
